name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  TINI_VERSION: v0.19.0
  TINI_KEY: 595E85A6B1B4779EA4DAAEC70B588DFF0527A9B7

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ibotta/tini-static:${{ env.TINI_VERSION }}
            ibotta/tini-static:latest
          build-args: |
            TINI_VERSION=${{ env.TINI_VERSION }}
            TINI_KEY=${{ env.TINI_KEY }}
